name: Build and Deploy Docker Image

on:
  push:
    branches:
      - purfect # Chạy workflow khi có thay đổi trên nhánh 'purfect'
  pull_request:
    branches:
      - purfect # Chạy workflow khi có pull request đến nhánh 'purfect'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout mã nguồn
      - name: Checkout code
        uses: actions/checkout@v2

      # Bước 2: Cài đặt Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Bước 3: Login vào Docker Hub (hoặc registry khác)
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Create .env file
        run: |
          echo "NEXT_PUBLIC_PAYPAL_CLIENT_ID=${{ secrets.NEXT_PUBLIC_PAYPAL_CLIENT_ID }}" > .env
          echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" >> .env
          echo "SHOPIFY_STORE_URL=${{ secrets.SHOPIFY_STORE_URL }}" >> .env.local
          echo "SHOPIFY_STOREFRONT_ACCESS_TOKEN=${{ secrets.SHOPIFY_STOREFRONT_ACCESS_TOKEN }}" >> .env.local
          echo "DOMAIN=${{ secrets.DOMAIN }}" >> .env.local
          echo "SHOPIFY_API_SECRET=${{ secrets.SHOPIFY_API_SECRET }}" >> .env.local

      # Bước 4: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t langhoangtien/purfect-fe:${{ github.sha }} .

      # Bước 5: Push Docker image lên Docker Hub (hoặc registry khác)
      - name: Push Docker image
        run: |
          docker push langhoangtien/purfect-fe:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Bước 1: Checkout mã nguồn
      - name: Checkout code
        uses: actions/checkout@v2

      # Bước 2: SSH vào server để deploy container
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull langhoangtien/purfect-fe:${{ github.sha }}
            if [ $(docker ps -a -q -f name=purfect-fe-container) ]; then
            # Nếu container tồn tại, dừng và xóa nó
              docker stop purfect-fe-container
              docker rm purfect-fe-container
            fi
            # Tạo container mới từ image vừa pull
            docker run -d -p 5000:5000 --name purfect-fe-container langhoangtien/purfect-fe:${{ github.sha }}
